version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "29093:29093"
      - "29094:29094"
    environment:
      # Zookeeper
      ZOOKEEPER_SASL_ENABLED: "false"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # General
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"


      # Listeners
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SSL:SSL,SASL_SSL:SASL_SSL,PLAINTEXT:PLAINTEXT"
      KAFKA_LISTENERS: "SASL_SSL://kafka:9092,SSL://kafka:9093,PLAINTEXT://kafka:9094"
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka:9092,SSL://kafka:9093,PLAINTEXT://kafka:9094"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"

      # SASL
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/jaas.conf"

      # SSL
      KAFKA_SSL_KEYSTORE_FILENAME: kafka.keystore.jks
      KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.truststore.jks
      KAFKA_SSL_KEYSTORE_CREDENTIALS: creds
      KAFKA_SSL_KEY_CREDENTIALS: creds
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: creds

    volumes:
      - ./secrets:/etc/kafka/secrets